### PR TITLE
Add config for EPEL

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by gotmax23** [comment]
The plain EPEL 8 and EPEL 9 tests should run on actual RHEL and not CentOS Stream. Running them on CentOS Stream is wrong and may cause false positives or false negatives.

**Comment by msrb** [comment]
Yep, but we don't have that option :/ These are all the composes that we can use for testing right now: https://api.dev.testing-farm.io/v0.1/composes

**Comment by gotmax23** [comment]
> Yep, but we don't have that option :/ These are all the composes that we can use for testing right now: https://api.dev.testing-farm.io/v0.1/composes

That's unfortunate. Is it possible to work within Red Hat to get RHEL instances added? Is using something like Almalinux or Rocky Linux an option?

**Comment by msrb** [comment]
@gotmax23 I will try to ask around. Maybe there is already a way how Fedora can get hands on RHEL subscriptions.

**Comment by carlwgeorge** [comment]
@gotmax23 is correct.  EPEL Next exists because when libraries change in RHEL, they already changed in CentOS Stream six months earlier.  As-is this config will lead to both false positives (package installs correctly in CI but fails on actual RHEL which doesn't have a dependency yet) and false negatives (package fails to install in CI but installs correctly on actual RHEL).

It is also worth mentioning that EPEL Next is a layer on top of EPEL.  If you only have EPEL Next on CentOS Stream, you will find many packages that fail to install due to missing dependencies that are in EPEL.  I'm not sure if that's reflected in this config or not.  So you'll need:

- RHEL 8 + EPEL 8
- CentOS Stream 8 + EPEL 8 + EPEL 8 Next
- RHEL 9 + EPEL 9
- CentOS Stream 9 + EPEL 9 + EPEL 9 Next

In theory, there should be no problem with Fedora getting RHEL.  The project already has access to RHEL content inside Koji in order to build EPEL in the first place.

**Comment by msrb** [comment]
I added the "RHEL for Fedora" question to the agenda for the next Fedora QE/Testing Farm/tmt meeting.

**Comment by thrix** [comment]
Yeah, needs discussion, like we are happy to support it, like makes sense to be able to test against released RHEL also in public

**Pull request merged**
